CREATE TABLE IF NOT EXISTS token (
    token TEXT NOT NULL PRIMARY KEY,
    expires_at DATETIME NOT NULL
);
CREATE TABLE IF NOT EXISTS data (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    value NUMERIC(30, 6) NOT NULL,
    value_out NUMERIC(30,6),
    value_current NUMERIC(30,6),
    synced BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS logs (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    log TEXT NOT NULL
);
