on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
            - target: x86_64-unknown-linux-musl
              archive: tar.gz tar.xz tar.zst
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install protoc
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler
          cp /usr/bin/protoc $GITHUB_WORKSPACE/protoc
          chmod +x $GITHUB_WORKSPACE/protoc

      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROTOC: ./protoc
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          EXTRA_FILES: ".env.sample"
