permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install protoc
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler
          echo "PROTOC=/usr/bin/protoc" >> $GITHUB_ENV

      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          PROTOC: ${{ env.PROTOC }}

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: ...
          target: ${{ matrix.target }}
          tar: unix
          include: .env.sample
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}
